// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 2.0.0,
// any modifications will be overwritten.
// ==============================================================

package org.apache.maven.model;

/**
 * Describes the prerequisites a project can have.
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
public class Prerequisites
    implements java.io.Serializable, Cloneable, InputLocationTracker
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * 
     *             For a plugin project (packaging is
     * <code>maven-plugin</code>), the minimum version of
     *             Maven required to use the resulting plugin.<br>
     *             In Maven 2, this was also specifying the minimum
     * version of Maven required to build a
     *             project, but this usage is <b>deprecated</b> in
     * Maven 3 and not checked any more: use
     *             the <a
     * href="https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html">Maven
     * Enforcer Plugin's
     *             <code>requireMavenVersion</code> rule</a>
     * instead.
     *             
     *           
     */
    private String maven = "2.0";

    /**
     * Field locations.
     */
    private java.util.Map<Object, InputLocation> locations;

    /**
     * Field location.
     */
    private InputLocation location;

    /**
     * Field mavenLocation.
     */
    private InputLocation mavenLocation;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method clone.
     * 
     * @return Prerequisites
     */
    public Prerequisites clone()
    {
        try
        {
            Prerequisites copy = (Prerequisites) super.clone();

            if ( copy.locations != null )
            {
                copy.locations = new java.util.LinkedHashMap( copy.locations );
            }

            return copy;
        }
        catch ( Exception ex )
        {
            throw (RuntimeException) new UnsupportedOperationException( getClass().getName()
                + " does not support clone()" ).initCause( ex );
        }
    } //-- Prerequisites clone()

    /**
     * 
     * 
     * @param key a key object.
     * @return InputLocation
     */
    public InputLocation getLocation( Object key )
    {
        if ( key instanceof String )
        {
            switch ( ( String ) key )
            {
                case "" :
                {
                    return this.location;
                }
                case "maven" :
                {
                    return mavenLocation;
                }
                default :
                {
                    return getOtherLocation( key );
                }
                }
            }
            else
            {
                return getOtherLocation( key );
            }
    } //-- InputLocation getLocation( Object )

    /**
     * Get for a plugin project (packaging is
     * <code>maven-plugin</code>), the minimum version of
     *             Maven required to use the resulting plugin.<br>
     *             In Maven 2, this was also specifying the minimum
     * version of Maven required to build a
     *             project, but this usage is <b>deprecated</b> in
     * Maven 3 and not checked any more: use
     *             the <a
     * href="https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html">Maven
     * Enforcer Plugin's
     *             <code>requireMavenVersion</code> rule</a>
     * instead.
     * 
     * @return String
     */
    public String getMaven()
    {
        return this.maven;
    } //-- String getMaven()

    /**
     * 
     * 
     * @param key a key object.
     * @param location a location object.
     */
    public void setLocation( Object key, InputLocation location )
    {
        if ( key instanceof String )
        {
            switch ( ( String ) key )
            {
                case "" :
                {
                    this.location = location;
                    return;
                }
                case "maven" :
                {
                    mavenLocation = location;
                    return;
                }
                default :
                {
                    setOtherLocation( key, location );
                    return;
                }
            }
        }
        else
        {
            setOtherLocation( key, location );
        }
    } //-- void setLocation( Object, InputLocation )

    /**
     * 
     * 
     * @param key a key object.
     * @param location a location object.
     */
    public void setOtherLocation( Object key, InputLocation location )
    {
        if ( location != null )
        {
            if ( this.locations == null )
            {
                this.locations = new java.util.LinkedHashMap<Object, InputLocation>();
            }
            this.locations.put( key, location );
        }
    } //-- void setOtherLocation( Object, InputLocation )

    /**
     * 
     * 
     * @param key a key object.
     * @return InputLocation
     */
    private InputLocation getOtherLocation( Object key )
    {
        return ( locations != null ) ? locations.get( key ) : null;
    } //-- InputLocation getOtherLocation( Object )

    /**
     * Set for a plugin project (packaging is
     * <code>maven-plugin</code>), the minimum version of
     *             Maven required to use the resulting plugin.<br>
     *             In Maven 2, this was also specifying the minimum
     * version of Maven required to build a
     *             project, but this usage is <b>deprecated</b> in
     * Maven 3 and not checked any more: use
     *             the <a
     * href="https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html">Maven
     * Enforcer Plugin's
     *             <code>requireMavenVersion</code> rule</a>
     * instead.
     * 
     * @param maven a maven object.
     */
    public void setMaven( String maven )
    {
        this.maven = maven;
    } //-- void setMaven( String )

}
