name: quality check

on:
 pull_request:
   branches: [ master ]
 push:
   branches: [ master ]
       
jobs:
  # Check all tests pass & quality gate
  check-tests-and-quality-gate:
    runs-on: ubuntu-latest
    steps:     
    - name: Checkout project
      uses: actions/checkout@v2    
      with:
        fetch-depth: 0
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 11        
    - name: Set up Maven cache
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2        
    - name: Run tests
      run: mvn -B test verify -Pgenerate.reports.jacoco
    - name: Check quality with SonarCloud
      run: mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar  -Dsonar.branch.name=$(echo "${{ github.ref }}" | tr '/' ' ' | awk '{ print $3 }')  -Dsonar.projectKey=$(echo "${{ github.repository }}" | tr '/' '_') -Dsonar.organization=${{ github.actor }} -Dsonar.host.url=https://sonarcloud.io -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
